# Generated by Django 3.1.4 on 2020-12-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='expired',
            new_name='frozen',
        ),
        migrations.RemoveField(
            model_name='post',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='old_price',
        ),
    ]
