# Generated by Django 3.1.4 on 2020-12-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals_app', '0002_auto_20201216_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='frozen',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='post',
            name='frozen_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frozen_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
